# Model Configs
draft:
  quantized: true
  params:
    pretrained_model_name_or_path: "models/google__gemma-3-270m-it"

target: 
  quantized: true
  params:
    pretrained_model_name_or_path: "models/google__gemma-3-4b-it"
    
# Generation Configs
device: "cuda:1"
summary_file_name: "gemma-3-d270m-t4b-it" 
model_collection: "gemma-3"
max_new_tokens: 256
k: 2

# Dataset configs
batch_size: 4
max_length: 512
num_samples: 20
dataset:
  path: "openai/gsm8k"
  name: "main"
